In [2]:
import os
import natsort
import glob
import numpy as np
masks_path ="/home/zwhy/QT_project/labeling_tool/test_data/segmented_images/masks"

masks = natsort.natsorted(glob.glob(os.path.join(masks_path, "*.npy")))

index = 0

#read the mask
mask = np.load(masks[index])
print(mask.shape)

print(mask)



(720, 720)
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [18 18 18 ...  0  0  0]
 [18 18 18 ...  0  0  0]
 [18 18 18 ...  0  0  0]]
